"""Generate docs/CHANGELOG.md from the git commit history.

Usage:  python scripts/generate_changelog.py
Runs in CI via .github/workflows/changelog.yml on every push to main;
can also be run locally before committing.

Commits are grouped by month, newest first, each linking to GitHub.
The changelog's own bot commits are excluded to avoid noise.
"""

import subprocess
from collections import OrderedDict
from datetime import date
from pathlib import Path

REPO_URL = "https://github.com/thatobabusi/thatobabusi"
EXCLUDE_SUBJECTS = ("chore: update docs/CHANGELOG.md",
                    "chore: update github-metrics.svg",
                    "chore: refresh automated docs",
                    "chore: regenerate code cards")

MONTHS = ("January", "February", "March", "April", "May", "June", "July",
          "August", "September", "October", "November", "December")

HEADER = """\
# Changelog

All notable changes to this profile, straight from the commit history.

> Auto-generated by [`scripts/generate_changelog.py`](../scripts/generate_changelog.py)
> via the [Changelog workflow](../.github/workflows/changelog.yml) — do not edit by hand.
> For curated release notes see [RELEASES.md](RELEASES.md).

"""


def git_log() -> list[tuple[str, str, str, str]]:
    """Return (full_hash, short_hash, iso_date, subject) tuples, newest first."""
    out = subprocess.run(
        ["git", "log", "--pretty=format:%H%x09%h%x09%ad%x09%s", "--date=short"],
        capture_output=True, text=True, check=True,
    ).stdout
    rows = []
    for line in out.splitlines():
        full, short, day, subject = line.split("\t", 3)
        if any(subject.startswith(s) for s in EXCLUDE_SUBJECTS):
            continue
        rows.append((full, short, day, subject))
    return rows


def esc(s: str) -> str:
    """Neutralise markdown control characters in commit subjects."""
    for ch in r"\`*_[]<>":
        s = s.replace(ch, "\\" + ch)
    return s


def main() -> None:
    groups: "OrderedDict[str, list]" = OrderedDict()
    for full, short, day, subject in git_log():
        year, month, _ = day.split("-")
        key = f"{MONTHS[int(month) - 1]} {year}"
        groups.setdefault(key, []).append((full, short, day, subject))

    lines = [HEADER]
    lines.append(f"_Last generated: {date.today().isoformat()}_\n")
    for heading, commits in groups.items():
        lines.append(f"\n## {heading}\n")
        for full, short, day, subject in commits:
            lines.append(f"- **{day}** — {esc(subject)} "
                         f"([`{short}`]({REPO_URL}/commit/{full}))")
        lines.append("")

    out_path = Path(__file__).resolve().parent.parent / "docs" / "CHANGELOG.md"
    out_path.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")
    print(f"wrote {out_path} ({sum(len(c) for c in groups.values())} commits, "
          f"{len(groups)} months)")


if __name__ == "__main__":
    main()
